export default {
  MEALS: 'Meals',
  FAVORITES: 'Favorites',
  CATEGORIES_SCREEN_TITLE: 'Meal Categories',
  FAVORITES_SCREEN_TITLE: 'Your Favorites',
  FILTERS_SCREEN_TITLE: 'Your Filters',
  FILTERS: 'Filters',
  INGREDIENTS: 'Ingredients',
  STEPS: 'Steps',
  EMPTY_MEALS_LIST: 'No meals found !',
  EMPTY_FAV_LIST: 'No favorite meals found !',
  EMPTY_CATEGORY_LIST: 'No Categories found !',
  AVAILABLE_FILTERS: 'Available Filters ',
  GLUTEN_FREE: 'Gluten-free',
  LACTOSE_FREE: 'Lactose-free',
  VEGAN: 'Vegan',
  VEGETARIAN: 'Vegetarian',
  SOMETHING_WENT_WRONG: 'Something went wrong',
  FILTERS_APPLIED: 'Filters Applied !',
  CANCEL: 'Cancel',
  OK: 'Ok',
  ERROR_OCCURED: 'An Error Occured !',
  ENTER_MEAL_TITLE: 'Enter a meal title',
  ENTER_MEAL_PRICE: 'Enter steps',
  CHOOSE_MEAL_IMAGE: 'Choose an image',
  UserMeals_ScreenTitle: 'My Meals',
  SAVE: 'Save',
  MEAL_TITLE_IS_REQUIRED: 'Meal title is required !',
  MEAL_STEPS_ARE_REQUIRED: 'Meal steps are required !',
  EMPTY_USER_MEAL_LIST: 'No Meals Added , Please add some !',
  ADD_MEAL: 'Add Meal',
  UPDATE_MEAL: 'Update Meal',
  MEAL_SUCCESSFULLY_ADDED: 'Meal added successfully !',
  YES: 'Yes',
  NO: 'No',
  ARE_YOU_SURE: 'Are you sure?',
  DELETE_THIS_ITEM: 'Do you really want to delete this item?',
  EMAIL_NOT_FOUND: 'This email could not be found!',
  INVALID_PASSWORD: 'This password is not valid!',
  ENTER_EMAIL: 'Enter email',
  ENTER_PASSWORD: 'Enter password',
  EMAIL_IS_REQUIRED: 'Email is required !',
  PASS_IS_REQUIRED: 'Password is required !',
  LOGIN: 'Login',
  SIGNUP: 'Sign up',
  EMAIL_IS_INVALID: 'Invalid email',
  EMAIL_ALREADY_EXISTS: 'This email alread exists',
  PASSWORD_MIN_LENGTH: 'Password should be atleast 6 characters long',
};
